### ISSUE TITLE
Weekly Scrum Nov 9

### ISSUE THREAD

**Issue by QuintonTracey** [BossNassTheGunganKing/Bookstore-SYSC4806#14]
What Have I done,
What will I do,
What is holding me back,

**Comment by trk20** [comment]
### This Week

- Outlined rough backend class diagram, including current and planned classes. Added the diagram to the readme so it is viewable by all team members (#17 ).
- Implemented object and repository classes and tests for #4 , #5 , #6 and related 
- Organized project structure #22 
- Pulled test/example objects out into separate class for reuse

### Next Week
- #8 
- #28 
- #25 and related logic
- Look into #24 
- Update class diagram on README

### Roadblocks
- None currently

**Comment by MikeHabs1999** [comment]
**This Week**

- Developed and refined controller methods to handle key operations:
  - Adding new authors and books.
  - Associating books with multiple authors through form submissions.
- Created and updated Thymeleaf HTML templates (newBook.html, author.html, allBooks.html) for form submission and data display. 
- Provided JUnit and MockMvc tests for validating the create new author and create new book functionalities.

**Next Week**

**Roadblocks**

**Comment by QuintonTracey** [comment]
### This week
Set the github up with CI and is up and running on azure. Implemented AuthorInfo, BookInfo and ListingInfo and their repos according to the initial design with minor changes. #3 #19 #20 

### Next week
Will begin to implementing more features such as, userlogins and cart functionality

### RoadBlocks

**Comment by punchow12** [comment]
Developed and Refined Controller Methods:

    Implemented methods to handle key operations, such as:
        - Linking pages together.

Created and Updated Thymeleaf HTML Templates:

    Built and refined templates (AllListings.html, listing.html, Book.html, etc) to:
        Facilitate form submissions.
        Display data clearly and effectively.
        Ensure a smooth user experience with intuitive layout and input validation.
        
 Next Week
 
 Add CSS to the Views created. and Cover Images serialization and deserialization.
 
 RoadBlock
 Merging all at once at the end was a headache due to changes in classes. Even so it was not an issue just an annoyance, next time I would pull from main more often rather than all at once.
