### ISSUE TITLE
Weekly Scrum Nov 14 24

### ISSUE THREAD

**Issue by QuintonTracey** [BossNassTheGunganKing/Bookstore-SYSC4806#37]
Below are notes for the scrum detailing for each member:

- What have they done
- What they will do 
- And what is holding them back

**Comment by QuintonTracey** [comment]
This week
No changes since Nov 9

This Week will work on
- #47  
- #49 
- #25
 
Nothing Holding Me back at the moment

**Comment by MikeHabs1999** [comment]
This week
No changes since Nov 9

This Week will work on:

- #38 
- #48 

I have no roadblocks at this time.

**Comment by trk20** [comment]
### This week
- #36 

### Next week
- #8 

No roadblocks at this time
