### ISSUE TITLE
Weekly Scrum Nov 24 24

### ISSUE THREAD

**Issue by QuintonTracey** [BossNassTheGunganKing/Bookstore-SYSC4806#56]
Below are notes for the scrum detailing for each member:

- What have they done

- What they will do

- And what is holding them back

**Comment by QuintonTracey** [comment]
This Week worked on:
- #47  
- #49 
- #25
- #57 

Will Work On:
- Presentation of Topic
- #39

RoadBlocks:
- #57 , resolving this issue but was overcome by troubleshooting with TA Curtis

**Comment by MikeHabs1999** [comment]
This Week worked on:

- #38 
- #48 

Will Work On:

- Presentation of Topic: 
- #39 
- #58

Roadblocks: 

- N/A

**Comment by trk20** [comment]
This week
- #8 
- #33 
- progress towards #53 

Next week:
- Topic presentation
- Assist with #39 
- Start on #46 time permitting

**Comment by punchow12** [comment]
This week 
- #40 
- made progress towards #43 
Next week 
- I will work on topic presentation
- #39 
- #42 
- #44 if possible.
Roadblocks:
- I was not able to get the HTML to display a discount in case that there is one, I believe you can do it in "thymeleaf if statement" but I commented out the code that was not ready for production.
