### ISSUE TITLE
Weekly Scrum Dec 04 24

### ISSUE THREAD

**Issue by QuintonTracey** [BossNassTheGunganKing/Bookstore-SYSC4806#71]
Below are notes for the scrum detailing for each member:

- What have they done

- What they will do

- And what is holding them back

**Comment by QuintonTracey** [comment]
This Week worked on:
- #69 
Will Work On:
- #70 

Roadblock's:
none at the moment

**Comment by MikeHabs1999** [comment]
This week worked on:

- #68 
- #67
- #13

Roadblock's:
None at the moment

**Comment by punchow12** [comment]
This Week worked on:
- #42 
- #13 

Roadblock's:
none at the moment
